### ISSUE TITLE
gyp error when installing in v0.11.13

### ISSUE THREAD

**Issue by yuvilio** [substack/clocker#14]
I failed installing clocker in v0.11.13.  Contrary to that installing in the latest stable (v0.10.31) worked fine.  Here's a trace and some info.

```bash
$ npm install -g clocker

...

make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
make: Leaving directory `/home/yuvilio/.nvm/v0.11.13/lib/node_modules/clocker/node_modules/level/node_modules/leveldown/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/yuvilio/.nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Linux 3.13.0-35-generic
gyp ERR! command "node" "/home/yuvilio/.nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/yuvilio/.nvm/v0.11.13/lib/node_modules/clocker/node_modules/level/node_modules/leveldown
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! leveldown@0.10.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@0.10.2 install script.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-35-generic
npm ERR! command "/home/yuvilio/.nvm/v0.11.13/bin/node" "/home/yuvilio/.nvm/v0.11.13/bin/npm" "install" "-g" "clocker"
npm ERR! cwd /home/yuvilio/ws/apps/node/nodeschool/promise-it-wont-hurt
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/yuvilio/ws/apps/node/nodeschool/promise-it-wont-hurt/npm-debug.log
npm ERR! not ok code 0
$ 
$ node --version
v0.11.13
$ uname -a
Linux kamitsukai 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ which node
/home/yuvilio/.nvm/v0.11.13/bin/node
$ 
```

**Comment by yoshuawuyts** [comment]
Also doesn't work on `io.js@1` at the moment. Updates to `level` must happen before it can run.

**Comment by fnogatz** [comment]
I've tested with `io.js@1.8`, `node.js@0.10` and `node.js@0.12`. Worked everywhere. Can you confirm?

**Comment by yoshuawuyts** [comment]
Aye, currently works on `io.js@1.6.3`

**Comment by fnogatz** [comment]
Okay, then I'll close it here. Thanks for your fast response :)

**Comment by yoshuawuyts** [comment]
^__________________^
