### ISSUE TITLE
--reportDay option for report command is broken after lib extraction

### ISSUE THREAD

**Issue by BeniRupp** [substack/clocker#46]
The `--reportDay` option of the report command is broken and should be fixed.

```
return date.getDate() + ' ' + monthNames[date.getMonth()] + ' ' + date.getFullYear()
              ^

TypeError: date.getDate is not a function
    at printDate (/Users/beni/.nvm/versions/node/v8.10.0/lib/node_modules/clocker/bin/index.js:623:15)
    at Command.report (/Users/beni/.nvm/versions/node/v8.10.0/lib/node_modules/clocker/bin/index.js:257:33)
    at Command.listener (/Users/beni/.nvm/versions/node/v8.10.0/lib/node_modules/clocker/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/Users/beni/.nvm/versions/node/v8.10.0/lib/node_modules/clocker/node_modules/commander/index.js:651:12)
    at Command.parse (/Users/beni/.nvm/versions/node/v8.10.0/lib/node_modules/clocker/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/Users/beni/.nvm/versions/node/v8.10.0/lib/node_modules/clocker/bin/index.js:170:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```

**Comment by fnogatz** [comment]
Fixed. I also spotted a missing `filter.lt`. Published as `clocker@1.15.2`.
